(function(){
const resumeUrl='https://drive.google.com/file/d/1Y54fF6NSf7t-7F6C4zBrXlQfCAeIgNY-/view?usp=sharing';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const boot=$('#bootScreen'),log=$('#bootLog'),bar=$('#bootProgress');
const lines=['[SYS] loading RI Portfolio OS','[WEBGL] terminal graphics online','[GITHUB] project stream mounted','[GLB] transit asset loader ready','[VOICE] speech synthesis ready','[QR] resume datalink verified','[READY] portfolio online'];
let bi=0;const bt=setInterval(()=>{if(bi<lines.length){const d=document.createElement('div');d.innerHTML=lines[bi].replace(/^\[([^\]]+)\]/,'<b>[$1]</b>');log?.appendChild(d);bi++;if(bar)bar.style.width=(bi/lines.length*100)+'%'}else{clearInterval(bt);setTimeout(()=>boot?.classList.add('hidden'),250)}},120);
$$('.typed-command').forEach((el,n)=>{const t=el.dataset.type||'';el.textContent='';setTimeout(()=>{let i=0;(function tick(){el.textContent=t.slice(0,i++);if(i<=t.length)setTimeout(tick,34)})()},n*300)});
const reveal=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.08});$$('.reveal').forEach(e=>reveal.observe(e));
const sections=$$('main section[id]'),links=$$('.system-nav a');addEventListener('scroll',()=>{let id=sections[0]?.id;const m=scrollY+150;sections.forEach(s=>{if(m>=s.offsetTop)id=s.id});links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+id))},{passive:true});
const started=performance.now(),clock=$('#runtimeClock');(function tick(){const ms=performance.now()-started,h=String(Math.floor(ms/3600000)).padStart(2,'0'),m=String(Math.floor(ms/60000%60)).padStart(2,'0'),s=String(Math.floor(ms/1000%60)).padStart(2,'0'),c=String(Math.floor(ms/10%100)).padStart(2,'0');if(clock)clock.textContent=`${h}:${m}:${s}:${c}`;requestAnimationFrame(tick)})();
const synth=speechSynthesis,vc=$('#voiceConsole'),vs=$('#voiceStatus'),vo=$('#voiceOrb');let current=null;
function voice(){const v=synth.getVoices();return v.find(x=>/David|Mark|Daniel|Alex|Fred|Male/i.test(x.name))||v.find(x=>/^en/i.test(x.lang))||v[0]}
function stop(){synth.cancel();current=null;$$('.speaker-btn').forEach(b=>b.classList.remove('speaking'));vo?.classList.remove('speaking');if(vs)vs.textContent='STANDBY'}
function speak(text,btn){stop();if(!text)return;const u=new SpeechSynthesisUtterance(text.replace(/\s+/g,' ').trim());u.voice=voice()||null;u.rate=.78;u.pitch=.48;u.onstart=()=>{current=btn;btn?.classList.add('speaking');vo?.classList.add('speaking');if(vs)vs.textContent='SPEAKING'};u.onend=u.onerror=stop;synth.speak(u)}
$$('.speaker-btn[data-speak-target]').forEach(b=>b.onclick=()=>{const el=document.getElementById(b.dataset.speakTarget);current===b&&synth.speaking?stop():speak(el?.innerText||'',b)});
$('#jarvisFab')?.addEventListener('click',()=>{const on=!vc?.classList.contains('open');vc?.classList.toggle('open',on);vc?.setAttribute('aria-hidden',String(!on))});$('#voiceClose')?.addEventListener('click',()=>vc?.classList.remove('open'));$('#stopVoice')?.addEventListener('click',stop);$('#speakIntro')?.addEventListener('click',()=>speak($('#heroSpeech')?.innerText||''));
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const cards=$$('.holo-panel:not(.transit-panel):not(.voice-console)');
cards.forEach((c,i)=>{c.classList.add('depth-card');c.style.setProperty('--card-delay',Math.min(i*18,180)+'ms');if(!reduced){c.addEventListener('pointermove',e=>{if(innerWidth<=820||e.pointerType==='touch')return;const r=c.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;c.style.setProperty('--rx',(-y*3.2)+'deg');c.style.setProperty('--ry',(x*4.2)+'deg');c.style.setProperty('--shine-x',((x+.5)*100)+'%');c.style.setProperty('--shine-y',((y+.5)*100)+'%');c.classList.add('depth-active')});c.addEventListener('pointerleave',()=>{c.style.setProperty('--rx','0deg');c.style.setProperty('--ry','0deg');c.classList.remove('depth-active')})}});
const mo=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('motion-in');mo.unobserve(e.target)}}),{threshold:.12});cards.forEach(c=>mo.observe(c));
$$('.section-rail h2,.project-card h3,.repo-card h3,.research-card h3,.certificate-copy h3,.log-status b').forEach(el=>{const t=el.textContent.trim();el.setAttribute('aria-label',t);el.innerHTML=t.split(/(\s+)/).map((p,i)=>/^\s+$/.test(p)?p:`<span class="word-reveal" style="--word-i:${i}">${p}</span>`).join('');mo.observe(el)});$$('.project-card p,.repo-card p,.research-card p,.exp-card p,.hero-copy').forEach(el=>{el.classList.add('copy-reveal');mo.observe(el)});
const out=$('#cliOutput'),input=$('#cliInput');function print(x){const p=document.createElement('p');p.innerHTML=x;out?.appendChild(p)}function go(id){document.getElementById(id)?.scrollIntoView({behavior:'smooth'})}
const cmds={help:()=>print('<b>commands</b>: identity profile experience projects research community certificate socials resume github linkedin website email speak stop clear'),identity:()=>go('home'),profile:()=>go('about'),experience:()=>go('experience'),projects:()=>go('projects'),research:()=>go('research'),community:()=>go('community'),certificate:()=>go('certifications'),socials:()=>go('socials'),resume:()=>{go('resume');print(resumeUrl)},github:()=>open('https://github.com/roronoa2003','_blank'),linkedin:()=>open('https://www.linkedin.com/in/rohan-iyer-461787264','_blank'),website:()=>open('https://www.rohaniyer.com','_blank'),email:()=>location.href='mailto:rohan.iyer5603@gmail.com',speak:()=>speak('Welcome to Rohan Iyer Portfolio.'),stop,clear:()=>{if(out)out.innerHTML=''}};
$('#cliForm')?.addEventListener('submit',e=>{e.preventDefault();const v=(input?.value||'').trim();if(!v)return;print(`<span class="prompt">visitor@ri:~$</span> ${v.replace(/[<>]/g,'')}`);const c=v.toLowerCase().split(/\s+/)[0];cmds[c]?cmds[c]():print(`<b>bash</b>: ${c}: command not found`);input.value=''});
if(!window.THREE)return;
const mobile=()=>innerWidth<=820;
const ac=$('#holoCanvas');if(ac){const r=new THREE.WebGLRenderer({canvas:ac,alpha:true,antialias:!mobile()}),s=new THREE.Scene(),c=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,80);c.position.z=10;const n=mobile()?220:650,p=new Float32Array(n*3),col=new Float32Array(n*3),pal=[new THREE.Color(0x39ff88),new THREE.Color(0xff4fd8),new THREE.Color(0xffd75f)];for(let i=0;i<n;i++){p[i*3]=(Math.random()-.5)*30;p[i*3+1]=(Math.random()-.5)*18;p[i*3+2]=(Math.random()-.5)*18-4;const q=pal[i%3];col[i*3]=q.r;col[i*3+1]=q.g;col[i*3+2]=q.b}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(p,3));g.setAttribute('color',new THREE.BufferAttribute(col,3));const pts=new THREE.Points(g,new THREE.PointsMaterial({size:.03,vertexColors:true,transparent:true,opacity:.32}));s.add(pts);function rs(){r.setSize(innerWidth,innerHeight);r.setPixelRatio(Math.min(devicePixelRatio,1.4));c.aspect=innerWidth/innerHeight;c.updateProjectionMatrix()}rs();addEventListener('resize',rs);(function a(){pts.rotation.y+=.00015;r.render(s,c);requestAnimationFrame(a)})()}
const canvas=$('#projectTransitCanvas'),stage=$('#projectTransitStage');if(!canvas||!stage)return;
const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:!mobile(),powerPreference:'high-performance'});renderer.outputColorSpace=THREE.SRGBColorSpace;const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(42,1,.1,100);camera.position.set(0,1.15,mobile()?12.8:11.2);camera.lookAt(0,0,0);scene.add(new THREE.HemisphereLight(0xbaffd2,0x050505,1.5));const dl=new THREE.DirectionalLight(0xffffff,1.2);dl.position.set(3,6,7);scene.add(dl);
const green=0x39ff88,pink=0xff4fd8,yellow=0xffd75f,map=new THREE.Group();map.rotation.x=-.12;scene.add(map);
const projects=[['Kubera — AI Finance Manager','KUBERA','2024','project-kubera','https://github.com/roronoa2003/Kubera'],['Paytm Logo Detection in Cricket','PAYTM CV','2025','project-paytm','https://github.com/roronoa2003/paytm-logo-detection'],['ResMatch - AI-Powered Resume Matching Platform','RESMATCH','2025','project-resmatch','https://github.com/roronoa2003/ResMatch_Deployed'],['Setu — Project Allocation Tool','SETU','2026','project-setu',''],['Upper Celestials Ops Dashboard','UC OPS','2026','project-uc-ops','https://github.com/roronoa2003/uc-dashboard'],['Organisational Agentic Digital Twin Platform','AGENTIC TWIN','2026','project-digital-twin','https://github.com/roronoa2003/directors']];
const stops=[[-4.8,-1.35,.25],[-3.05,1.15,-.22],[-1.15,-.2,.35],[.72,1.28,-.28],[2.68,-.72,.22],[4.75,.82,-.08]].map(v=>new THREE.Vector3(...v)),curve=new THREE.CatmullRomCurve3(stops,false,'catmullrom',.12),route=curve.getPoints(mobile()?110:180);map.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(route),new THREE.LineBasicMaterial({color:green,transparent:true,opacity:.85})));
const passed=new THREE.Line(new THREE.BufferGeometry().setFromPoints(route),new THREE.LineBasicMaterial({color:yellow,transparent:true,opacity:.95}));passed.geometry.setDrawRange(0,1);map.add(passed);
const rings=[],meshes=[],labels=[],$labels=$('#stationLabels'),status=$('#transitStatus'),mcard=$('#transitMobileCard');stops.forEach((p,i)=>{const m=new THREE.Mesh(new THREE.SphereGeometry(.14,16,16),new THREE.MeshBasicMaterial({color:i%3===0?yellow:i%3===1?pink:green}));m.position.copy(p);m.userData.index=i;map.add(m);meshes.push(m);const q=new THREE.Mesh(new THREE.TorusGeometry(.25,.018,8,36),new THREE.MeshBasicMaterial({color:green}));q.position.copy(p);q.rotation.x=Math.PI/2;map.add(q);rings.push(q);const b=document.createElement('button');b.type='button';b.className='station-label';b.innerHTML=`<i>STOP ${String(i+1).padStart(2,'0')} // ${projects[i][2]}</i><strong>${projects[i][1]}</strong>`;b.onclick=e=>{e.stopPropagation();select(i,true)};$labels?.appendChild(b);labels.push(b)});
const carrier=new THREE.Group();map.add(carrier);const fallback=new THREE.Mesh(new THREE.BoxGeometry(.72,.38,.34),new THREE.MeshStandardMaterial({color:pink,emissive:0x24021b,roughness:.35}));carrier.add(fallback);const beacon=new THREE.Mesh(new THREE.TorusGeometry(.22,.015,8,36),new THREE.MeshBasicMaterial({color:yellow}));beacon.rotation.x=Math.PI/2;beacon.position.y=.55;carrier.add(beacon);
let selected=0,seg=0,prog=0,paused=false,dwell=1.2,end=0;const dur=mobile()?2.8:3.1,pause=$('#transitPause');function stat(i,state='ARRIVING'){const p=projects[i];if(status)status.innerHTML=`<span>BUS 01 // ${state}</span><b>${p[1]}</b><small>${p[2]} // PROJECT ${String(i+1).padStart(2,'0')} OF 06</small>`}function card(i){if(!mcard)return;const p=projects[i],a=p[4]?`<a href="${p[4]}" target="_blank">REPO ↗</a>`:`<a href="#${p[3]}">VIEW ↓</a>`;mcard.innerHTML=`<span class="tm-index">${String(i+1).padStart(2,'0')}</span><span class="tm-copy"><b>${p[0]}</b><span>${p[2]} // PROJECT STOP</span></span>${a}`}function select(i,user=false){selected=Math.max(0,Math.min(5,i));labels.forEach((x,j)=>x.classList.toggle('active',j===selected));rings.forEach((x,j)=>x.material.color.setHex(j===selected?pink:j<selected?yellow:green));card(selected);stat(selected,user?'SELECTED':'ARRIVING');if(user){seg=Math.min(selected,4);prog=selected===5?1:0;dwell=1;carrier.position.copy(stops[selected])}}function restart(){seg=0;prog=0;dwell=1.3;end=0;paused=false;if(pause)pause.textContent='[ PAUSE ]';passed.geometry.setDrawRange(0,1);select(0);carrier.position.copy(stops[0])}function next(){const n=Math.min(5,selected+1);if(n===selected)return restart();select(n,true)}pause?.addEventListener('click',()=>{paused=!paused;pause.textContent=paused?'[ RESUME ]':'[ PAUSE ]'});$('#transitReplay')?.addEventListener('click',restart);$('#transitNext')?.addEventListener('click',next);
(async()=>{try{const {GLTFLoader}=await import('https://cdn.jsdelivr.net/npm/three@0.166.1/examples/jsm/loaders/GLTFLoader.js/+esm'),loader=new GLTFLoader(),fit=(m,n)=>{const b=new THREE.Box3().setFromObject(m),z=b.getSize(new THREE.Vector3()),ce=b.getCenter(new THREE.Vector3()),d=Math.max(z.x,z.y,z.z)||1;m.scale.setScalar(n/d);m.position.sub(ce.multiplyScalar(m.scale.x))};loader.load('https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Models@main/2.0/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb',g=>{fit(g.scene,mobile()?.92:1.08);g.scene.rotation.y=Math.PI/2;g.scene.position.y=-.14;carrier.remove(fallback);carrier.add(g.scene);stat(selected,'GLB VEHICLE ONLINE')});loader.load('3d_character_young_boy.glb',g=>{fit(g.scene,mobile()?.72:.88);g.scene.position.copy(stops[5]).add(new THREE.Vector3(.35,.12,-.3));g.scene.rotation.y=-.6;map.add(g.scene)})}catch(e){stat(selected,'FALLBACK VEHICLE')}})();
let drag=false,x0=0,y0=0,ry=0,rx=-.12;stage.addEventListener('pointerdown',e=>{drag=true;x0=e.clientX;y0=e.clientY;stage.setPointerCapture?.(e.pointerId)});stage.addEventListener('pointermove',e=>{if(!drag)return;ry=Math.max(-.28,Math.min(.28,(e.clientX-x0)*.004));rx=Math.max(-.26,Math.min(.05,-.12+(e.clientY-y0)*.003))});stage.addEventListener('pointerup',()=>drag=false);
function resize(){const r=stage.getBoundingClientRect();renderer.setSize(r.width,r.height,false);renderer.setPixelRatio(Math.min(devicePixelRatio,mobile()?1.25:1.6));camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}resize();new ResizeObserver(resize).observe(stage);function screen(p,el){const r=stage.getBoundingClientRect(),q=p.clone().applyMatrix4(map.matrixWorld).project(camera);el.style.left=((q.x*.5+.5)*r.width)+'px';el.style.top=((-q.y*.5+.5)*r.height-(mobile()?25:36))+'px'}select(0);carrier.position.copy(stops[0]);const tc=new THREE.Clock();(function anim(){const dt=Math.min(tc.getDelta(),.05),t=tc.elapsedTime;map.rotation.y+=(ry-map.rotation.y)*.06;map.rotation.x+=(rx-map.rotation.x)*.06;if(!paused){if(end>0){end-=dt;if(end<=0)restart()}else if(dwell>0)dwell-=dt;else if(seg<5){prog+=dt/dur;const l=Math.min(prog,1),ct=THREE.MathUtils.lerp(seg/5,(seg+1)/5,l),p=curve.getPoint(ct),tan=curve.getTangent(ct);carrier.position.copy(p);carrier.rotation.z=Math.atan2(tan.y,tan.x);passed.geometry.setDrawRange(0,Math.max(2,Math.floor(ct*(route.length-1))+1));if(l>=1){seg++;prog=0;select(seg);dwell=1.35;if(seg===5){end=3;stat(5,'LATEST STOP')}}else stat(seg+1,'EN ROUTE TO')}}beacon.rotation.z+=.03;beacon.scale.setScalar(1+Math.sin(t*4)*.15);stops.forEach((p,i)=>screen(p,labels[i]));renderer.render(scene,camera);requestAnimationFrame(anim)})();
})();
