(function(){
  'use strict';
  if(window.__RI_POLISH_LOADED__)return;window.__RI_POLISH_LOADED__=true;
  const reduced=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const home=document.getElementById('home');
  if(home&&!home.querySelector('.hiring-resume')){
    const card=document.createElement('article');card.className='holo-panel hiring-resume';card.setAttribute('aria-label','Resume quick access');
    card.innerHTML=`<div class="panel-header"><span>HIRING MODE // RESUME FIRST</span><span>CV | PRIORITY DATALINK</span></div><div class="hiring-resume-body"><a class="hiring-qr" href="https://drive.google.com/file/d/1Y54fF6NSf7t-7F6C4zBrXlQfCAeIgNY-/view?usp=sharing" target="_blank" rel="noopener" aria-label="Open Rohan Iyer resume"><img src="resume-qr.png" alt="QR code to open Rohan Iyer resume"><span>SCAN RESUME</span></a><div class="hiring-copy"><div class="cmd-row"><span class="prompt">recruiter@portfolio:~$</span> <span data-scroll-type="open --resume rohan_iyer.pdf"></span><span class="cursor">_</span></div><div class="hiring-kicker">FAST ACCESS // MASTER OF COMPUTER SCIENCE @ UIUC</div><h2 data-scroll-type="Resume ready for review">Resume ready for review</h2><p>Scan the QR or open the resume directly. The rest of this portfolio keeps the same terminal system while giving you deeper access to experience, projects, research, and technical work.</p><div class="hiring-actions"><a class="primary-resume-btn" href="https://drive.google.com/file/d/1Y54fF6NSf7t-7F6C4zBrXlQfCAeIgNY-/view?usp=sharing" target="_blank" rel="noopener">[ OPEN RESUME ↗ ]</a><a href="#experience">[ EXPERIENCE ↓ ]</a><a href="#projects">[ PROJECTS ↓ ]</a></div></div><div class="hiring-status" aria-hidden="true"><span><i></i> RESUME LINK</span><b>ONLINE</b><span><i></i> QR TARGET</span><b>VERIFIED</b><span><i></i> MOBILE VIEW</span><b>READY</b></div></div>`;
    home.insertBefore(card,home.firstChild);
  }
  const dock=document.querySelector('.mobile-dock');if(dock)dock.innerHTML='<a class="dock-resume" href="#home"><b>CV</b><span>RESUME</span></a><a href="#experience"><b>03</b><span>EXP</span></a><a href="#projects"><b>04</b><span>WORK</span></a><a href="#socials"><b>↗</b><span>SOCIAL</span></a>';
  const revealTargets=[...document.querySelectorAll('.section-rail,.social-terminal,.hiring-resume,.content-section .holo-panel')];revealTargets.forEach((el,i)=>{el.classList.add('soft-reveal');el.style.setProperty('--soft-delay',`${Math.min((i%5)*42,168)}ms`)});
  if(reduced)revealTargets.forEach(el=>el.classList.add('is-in'));else{const ro=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-in');ro.unobserve(e.target)}}),{threshold:.07,rootMargin:'0px 0px -5% 0px'});revealTargets.forEach(el=>ro.observe(el))}
  const targets=[...new Set([...document.querySelectorAll('[data-scroll-type]'),...document.querySelectorAll('.section-rail h2,.project-card h3,.repo-card h3,.research-card h3')])];
  const typeOne=el=>{if(el.dataset.typedDone==='1')return;const source=el.dataset.scrollType||el.textContent.trim();el.dataset.typedDone='1';el.setAttribute('aria-label',source);if(reduced||source.length>88){el.textContent=source;el.classList.add('type-complete');return}el.textContent='';el.classList.add('scroll-type-live');let i=0;const speed=innerWidth<=620?10:14;(function tick(){i++;el.textContent=source.slice(0,i);if(i<source.length)setTimeout(tick,speed);else{el.classList.remove('scroll-type-live');el.classList.add('type-complete')}})()};
  if('IntersectionObserver'in window){const to=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){typeOne(e.target);to.unobserve(e.target)}}),{threshold:.30,rootMargin:'0px 0px -10% 0px'});targets.forEach(el=>to.observe(el))}else targets.forEach(typeOne);
  if(innerWidth<=900&&'IntersectionObserver'in window){const links=[...document.querySelectorAll('.system-nav a')],sections=links.map(a=>document.querySelector(a.getAttribute('href'))).filter(Boolean);const no=new IntersectionObserver(es=>{const top=es.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!top)return;const link=links.find(a=>a.hash===`#${top.target.id}`);link&&link.scrollIntoView({behavior:reduced?'auto':'smooth',block:'nearest',inline:'center'})},{threshold:[.15,.35,.55],rootMargin:'-20% 0px -62% 0px'});sections.forEach(s=>no.observe(s))}
})();
