(function(){
'use strict';
const stage=document.getElementById('projectTransitStage'),canvas=document.getElementById('projectTransitCanvas'),status=document.getElementById('transitStatus'),labelsRoot=document.getElementById('stationLabels'),mobileCard=document.getElementById('transitMobileCard');
const pauseBtn=document.getElementById('transitPause'),replayBtn=document.getElementById('transitReplay'),nextBtn=document.getElementById('transitNext');
if(!stage||!canvas)return;
const fail=(m,e)=>{if(status)status.textContent=m;stage.classList.add('three-error');if(e)console.error('[RI 3D]',e)};
if(!window.THREE){fail('3D ENGINE UNAVAILABLE');return}
const T=window.THREE,GLTFLoader=window.RI_GLTFLoader||null;
const isMobile=()=>innerWidth<=780,saveData=!!(navigator.connection&&navigator.connection.saveData),weak=(navigator.deviceMemory&&navigator.deviceMemory<=4)||(navigator.hardwareConcurrency&&navigator.hardwareConcurrency<=4),low=isMobile()||saveData||weak,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const P=[
{name:'Kubera',full:'Kubera — AI Finance Manager',year:'2024',target:'project-kubera',repo:'https://github.com/roronoa2003/Kubera',art:'kubera.png'},
{name:'Paytm CV',full:'Paytm Logo Detection in Cricket',year:'2025',target:'project-paytm',repo:'https://github.com/roronoa2003/paytm-logo-detection',art:'Paytm-Logo.png'},
{name:'ResMatch',full:'ResMatch – AI Resume Matching Platform',year:'2025',target:'project-resmatch',repo:'https://github.com/roronoa2003/ResMatch_Deployed'},
{name:'Setu',full:'Setu – AI Project Allocation Platform',year:'2026',target:'project-setu',repo:''},
{name:'UC Ops',full:'Upper Celestials Ops Dashboard',year:'2026',target:'project-uc-ops',repo:'https://github.com/roronoa2003/uc-dashboard',art:'uppercelestials.png'},
{name:'Agentic Twin',full:'Organisation-as-a-Service – Agentic Digital Twin',year:'2026',target:'project-digital-twin',repo:'https://github.com/roronoa2003/directors',art:'practus.png'}
];
const hud=document.createElement('div');hud.className='world-hud';hud.innerHTML='<div class="world-hud-left"><span class="world-chip"><i></i> LIVE 3D</span><span class="world-chip">'+(low?'MOBILE PERFORMANCE':'DESKTOP CINEMATIC')+'</span></div><div class="world-loader"><span>LOADING WORLD</span><div><i></i></div></div>';stage.appendChild(hud);
const loaderUI=hud.querySelector('.world-loader'),loaderBar=loaderUI&&loaderUI.querySelector('i');
let renderer;
try{renderer=new T.WebGLRenderer({canvas:canvas,alpha:false,antialias:!low,powerPreference:'high-performance',preserveDrawingBuffer:false})}catch(e){fail('WEBGL INITIALISATION FAILED',e);return}
renderer.setClearColor(0x060807,1);if('outputColorSpace'in renderer&&T.SRGBColorSpace)renderer.outputColorSpace=T.SRGBColorSpace;if(T.ACESFilmicToneMapping!==undefined){renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08}
renderer.shadowMap.enabled=!low;if(renderer.shadowMap.enabled&&T.PCFSoftShadowMap!==undefined)renderer.shadowMap.type=T.PCFSoftShadowMap;
canvas.style.opacity='1';canvas.style.visibility='visible';
const scene=new T.Scene();scene.background=new T.Color(0x060807);scene.fog=new T.FogExp2(0x060807,low?.036:.029);
const camera=new T.PerspectiveCamera(43,1,.1,140);let theta=.42,phi=.95,radius=low?18.8:16.8,tTheta=theta,tPhi=phi,tRadius=radius;
scene.add(new T.HemisphereLight(0xbfffd1,0x071008,low?1.15:1.35));
const sun=new T.DirectionalLight(0xfff7de,low?1.5:2.2);sun.position.set(-7,13,8);if(renderer.shadowMap.enabled){sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{near:1,far:38,left:-14,right:14,top:12,bottom:-12});sun.shadow.bias=-.0007}scene.add(sun);
const pinkFill=new T.PointLight(0xff5ac8,low?.7:1.25,24,2);pinkFill.position.set(-6,4,5);scene.add(pinkFill);
const greenFill=new T.PointLight(0x54f58a,low?.6:1.05,26,2);greenFill.position.set(7,5,-5);scene.add(greenFill);
const world=new T.Group();scene.add(world);const GREEN=0x54f58a,PINK=0xff5ac8,YELLOW=0xffe36e,groundY=-2.85;
const sky=new T.Mesh(new T.SphereGeometry(65,low?18:28,low?10:16),new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{top:{value:new T.Color(0x101a14)},bottom:{value:new T.Color(0x020302)},offset:{value:10},exponent:{value:.75}},vertexShader:'varying vec3 vWorldPosition;void main(){vec4 w=modelMatrix*vec4(position,1.0);vWorldPosition=w.xyz;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'uniform vec3 top;uniform vec3 bottom;uniform float offset;uniform float exponent;varying vec3 vWorldPosition;void main(){float h=normalize(vWorldPosition+vec3(0.0,offset,0.0)).y;gl_FragColor=vec4(mix(bottom,top,max(pow(max(h,0.0),exponent),0.0)),1.0);}'}));scene.add(sky);
const ground=new T.Mesh(new T.PlaneGeometry(42,30),new T.MeshStandardMaterial({color:0x101510,roughness:.94,metalness:.02}));ground.rotation.x=-Math.PI/2;ground.position.y=groundY;ground.receiveShadow=renderer.shadowMap.enabled;world.add(ground);
const grid=new T.GridHelper(34,34,0x23402a,0x142019);grid.position.y=groundY+.008;grid.material.transparent=true;grid.material.opacity=.4;world.add(grid);
const stops=[new T.Vector3(-6.4,-1.4,3.3),new T.Vector3(-4.1,.55,-2.2),new T.Vector3(-1.45,-.25,1.15),new T.Vector3(1,1.15,-2.8),new T.Vector3(3.65,-.15,1.65),new T.Vector3(6.25,1.15,-.8)],curve=new T.CatmullRomCurve3(stops,false,'catmullrom',.18);
function ribbon(path,width,n){const pos=[],uv=[],idx=[],up=new T.Vector3(0,1,0);for(let i=0;i<=n;i++){const u=i/n,p=path.getPoint(u),tan=path.getTangent(u).normalize();let side=new T.Vector3().crossVectors(up,tan).normalize();if(side.lengthSq()<.01)side.set(1,0,0);const l=p.clone().addScaledVector(side,width*.5),r=p.clone().addScaledVector(side,-width*.5);l.y-=.08;r.y-=.08;pos.push(l.x,l.y,l.z,r.x,r.y,r.z);uv.push(0,u*8,1,u*8);if(i<n){const a=i*2,b=a+1,c=a+2,d=a+3;idx.push(a,c,b,c,d,b)}}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(pos,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(idx);g.computeVertexNormals();return g}
const road=new T.Mesh(ribbon(curve,1.28,low?90:170),new T.MeshStandardMaterial({color:0x171b18,roughness:.78,metalness:.08}));road.receiveShadow=renderer.shadowMap.enabled;world.add(road);
const edgeMat=new T.MeshStandardMaterial({color:0x2b332d,roughness:.48,metalness:.58}),glowMat=new T.MeshBasicMaterial({color:GREEN,transparent:true,opacity:.5}),up=new T.Vector3(0,1,0);
function offsetCurve(sign){const pts=curve.getSpacedPoints(low?80:140).map((p,i,a)=>{const tan=curve.getTangent(i/(a.length-1)).normalize(),side=new T.Vector3().crossVectors(up,tan).normalize();return p.clone().addScaledVector(side,.66*sign).add(new T.Vector3(0,-.02,0))});return new T.CatmullRomCurve3(pts)}
world.add(new T.Mesh(new T.TubeGeometry(offsetCurve(1),low?80:140,.035,6,false),edgeMat),new T.Mesh(new T.TubeGeometry(offsetCurve(-1),low?80:140,.035,6,false),edgeMat),new T.Mesh(new T.TubeGeometry(curve,low?100:170,.017,5,false),glowMat));
const dashMat=new T.MeshBasicMaterial({color:YELLOW,transparent:true,opacity:.64});for(let i=4;i<64;i+=4){const u=i/64,p=curve.getPoint(u),tan=curve.getTangent(u).normalize(),d=new T.Mesh(new T.BoxGeometry(.34,.018,.035),dashMat);d.position.copy(p).add(new T.Vector3(0,-.045,0));d.quaternion.setFromUnitVectors(new T.Vector3(1,0,0),tan);world.add(d)}
let seed=1337;const rand=()=>{seed=seed*16807%2147483647;return(seed-1)/2147483646};
const nBuildings=low?24:58,boxGeo=new T.BoxGeometry(1,1,1),matA=new T.MeshStandardMaterial({color:0x151a16,roughness:.82,metalness:.13,emissive:0x071109,emissiveIntensity:.22}),matB=new T.MeshStandardMaterial({color:0x191319,roughness:.78,metalness:.12,emissive:0x130812,emissiveIntensity:.28}),aCount=Math.ceil(nBuildings*.65),bCount=nBuildings-aCount,cityA=new T.InstancedMesh(boxGeo,matA,aCount),cityB=new T.InstancedMesh(boxGeo,matB,bCount),dummy=new T.Object3D();let ai=0,bi=0;
for(let i=0;i<nBuildings;i++){const x=(rand()-.5)*28,z=(rand()-.5)*19;if(Math.abs(x)<8&&Math.abs(z)<5){i--;continue}const h=.8+rand()*4.5,w=.55+rand()*1.15,d=.55+rand()*1.15;dummy.position.set(x,groundY+h*.5,z);dummy.scale.set(w,h,d);dummy.rotation.y=rand()*.45;dummy.updateMatrix();if(i%3===0&&bi<bCount)cityB.setMatrixAt(bi++,dummy.matrix);else if(ai<aCount)cityA.setMatrixAt(ai++,dummy.matrix);else cityB.setMatrixAt(bi++,dummy.matrix)}
cityA.castShadow=cityB.castShadow=!low;cityA.receiveShadow=cityB.receiveShadow=renderer.shadowMap.enabled;world.add(cityA,cityB);
const treeN=low?9:22,trunks=new T.InstancedMesh(new T.CylinderGeometry(.06,.08,1,6),new T.MeshStandardMaterial({color:0x3a2a1c,roughness:1}),treeN),crowns=new T.InstancedMesh(new T.ConeGeometry(.36,1.15,8),new T.MeshStandardMaterial({color:0x17341f,roughness:.9}),treeN);
for(let i=0;i<treeN;i++){let x=(rand()-.5)*25,z=(rand()-.5)*17;if(Math.abs(x)<7&&Math.abs(z)<4){i--;continue}const s=.75+rand()*.65;dummy.position.set(x,groundY+.5*s,z);dummy.scale.set(s,s,s);dummy.rotation.y=rand()*Math.PI;dummy.updateMatrix();trunks.setMatrixAt(i,dummy.matrix);dummy.position.y=groundY+1.2*s;dummy.updateMatrix();crowns.setMatrixAt(i,dummy.matrix)}trunks.castShadow=crowns.castShadow=!low;world.add(trunks,crowns);
const postMat=new T.MeshStandardMaterial({color:0x303630,roughness:.45,metalness:.65}),bulbMat=new T.MeshBasicMaterial({color:YELLOW});for(let i=5;i<54;i+=6){const u=i/58,p=curve.getPoint(u),tan=curve.getTangent(u),side=new T.Vector3().crossVectors(up,tan).normalize(),base=p.clone().addScaledVector(side,(i%12===5?1:-1)*1.15),post=new T.Mesh(new T.CylinderGeometry(.025,.035,1.55,8),postMat),bulb=new T.Mesh(new T.SphereGeometry(.065,10,8),bulbMat);post.position.copy(base).add(new T.Vector3(0,.55,0));bulb.position.copy(base).add(new T.Vector3(0,1.34,0));world.add(post,bulb)}
function textTex(p,i){const c=document.createElement('canvas');c.width=768;c.height=256;const x=c.getContext('2d'),g=x.createLinearGradient(0,0,768,0);x.fillStyle='#070907';x.fillRect(0,0,768,256);g.addColorStop(0,'#54f58a');g.addColorStop(.6,'#ff5ac8');g.addColorStop(1,'#ffe36e');x.fillStyle=g;x.fillRect(0,0,10,256);x.fillStyle='#778078';x.font='24px monospace';x.fillText('STOP '+String(i+1).padStart(2,'0')+' // '+p.year,40,55);x.fillStyle='#f1f3ef';x.font='700 48px sans-serif';x.fillText(p.name.toUpperCase(),40,125);x.fillStyle='#54f58a';x.font='22px monospace';x.fillText('PROJECT JOURNEY // ROHAN IYER',40,182);x.strokeStyle='#2b312c';x.strokeRect(.5,.5,767,255);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;t.anisotropy=Math.min(4,renderer.capabilities.getMaxAnisotropy?renderer.capabilities.getMaxAnisotropy():1);return t}
const stationMeshes=[],rings=[],labelEls=[];if(labelsRoot)labelsRoot.innerHTML='';
stops.forEach((p,i)=>{const pr=P[i],accent=[YELLOW,PINK,GREEN][i%3],hub=new T.Group();hub.position.copy(p);world.add(hub);const slab=new T.Mesh(new T.CylinderGeometry(.76,.86,.18,32),new T.MeshStandardMaterial({color:0x171a17,roughness:.65,metalness:.25}));slab.position.y=-.18;slab.receiveShadow=renderer.shadowMap.enabled;hub.add(slab);const ring=new T.Mesh(new T.TorusGeometry(.78,.038,8,54),new T.MeshBasicMaterial({color:accent,transparent:true,opacity:.9}));ring.rotation.x=Math.PI/2;ring.position.y=-.07;hub.add(ring);rings.push(ring);const core=new T.Mesh(new T.CylinderGeometry(.22,.22,.16,24),new T.MeshStandardMaterial({color:accent,emissive:accent,emissiveIntensity:.35,roughness:.35,metalness:.22}));core.userData.index=i;core.position.y=-.02;hub.add(core);stationMeshes.push(core);[-.55,.55].forEach(px=>{const pole=new T.Mesh(new T.CylinderGeometry(.022,.028,1.45,8),postMat);pole.position.set(px,.65,-.36);hub.add(pole)});const canopy=new T.Mesh(new T.BoxGeometry(1.55,.08,.75),new T.MeshStandardMaterial({color:0x202520,roughness:.48,metalness:.42}));canopy.position.set(0,1.37,-.36);canopy.castShadow=!low;hub.add(canopy);const sign=new T.Mesh(new T.PlaneGeometry(1.72,.57),new T.MeshBasicMaterial({map:textTex(pr,i),toneMapped:false,side:T.DoubleSide}));sign.position.set(0,.93,-.765);sign.rotation.y=Math.PI;hub.add(sign);if(labelsRoot){const el=document.createElement('button');el.type='button';el.className='station-label';el.innerHTML='<i>STOP '+String(i+1).padStart(2,'0')+' · '+pr.year+'</i><strong>'+pr.name+'</strong>';el.setAttribute('aria-label',pr.full+', '+pr.year);el.addEventListener('click',()=>select(i,true));labelsRoot.appendChild(el);labelEls.push(el)}});
const vehicle=new T.Group();world.add(vehicle);const fallback=new T.Group();vehicle.add(fallback),fbBody=new T.Mesh(new T.BoxGeometry(1.25,.52,.62),new T.MeshStandardMaterial({color:PINK,emissive:0x240217,emissiveIntensity:.25,metalness:.35,roughness:.28})),fbCab=new T.Mesh(new T.BoxGeometry(.42,.45,.58),new T.MeshStandardMaterial({color:YELLOW,metalness:.25,roughness:.34}));fbBody.position.y=.25;fbCab.position.set(.46,.52,0);fbBody.castShadow=fbCab.castShadow=!low;fallback.add(fbBody,fbCab);const wMat=new T.MeshStandardMaterial({color:0x090909,roughness:.9});[[-.38,.06,.32],[.38,.06,.32],[-.38,.06,-.32],[.38,.06,-.32]].forEach(v=>{const w=new T.Mesh(new T.CylinderGeometry(.13,.13,.08,18),wMat);w.rotation.x=Math.PI/2;w.position.set(v[0],v[1],v[2]);fallback.add(w)});const headLight=new T.PointLight(YELLOW,low?1:2.2,4.5,2);headLight.position.set(.78,.42,.18);vehicle.add(headLight);
const manager=new T.LoadingManager();manager.onProgress=(u,l,t)=>{if(loaderBar)loaderBar.style.width=Math.round(l/Math.max(1,t)*100)+'%'};manager.onLoad=()=>{stage.classList.add('world-assets-ready');if(loaderUI){loaderUI.classList.add('done');setTimeout(()=>loaderUI.remove(),650)}};manager.onError=u=>console.warn('[RI 3D] Asset failed:',u);
const normalize=(o,target)=>{const box=new T.Box3().setFromObject(o),size=box.getSize(new T.Vector3()),center=box.getCenter(new T.Vector3()),s=target/(Math.max(size.x,size.y,size.z)||1);o.scale.setScalar(s);o.position.sub(center.multiplyScalar(s))};
const shadows=o=>o.traverse&&o.traverse(n=>{if(n.isMesh){n.castShadow=!low;n.receiveShadow=renderer.shadowMap.enabled}});
let mixer=null;
if(GLTFLoader){try{const gltf=new GLTFLoader(manager);gltf.load('assets/cesium-milk-truck.glb',g=>{const car=g.scene;normalize(car,1.75);shadows(car);car.rotation.y=Math.PI/2;car.position.y=.32;vehicle.remove(fallback);vehicle.add(car);if(g.animations&&g.animations.length){mixer=new T.AnimationMixer(car);g.animations.forEach(c=>mixer.clipAction(c).play())}setState(selected,'REAL GLB VEHICLE ONLINE')},undefined,e=>console.warn('[RI 3D] Vehicle fallback active.',e));if(!low)gltf.load('3d_character_young_boy.glb',g=>{const person=g.scene;normalize(person,1.55);shadows(person);person.rotation.y=-1.7;const root=new T.Group();root.position.copy(stops[5]).add(new T.Vector3(1.05,-.1,.35));root.add(person);world.add(root)},undefined,e=>console.warn('[RI 3D] Character asset skipped.',e))}catch(e){console.warn('[RI 3D] GLTF loader unavailable.',e)}}else{if(loaderUI)loaderUI.querySelector('span').textContent='WORLD READY · GLB FALLBACK';setTimeout(()=>loaderUI&&loaderUI.remove(),1200)}
if(!low){const texLoader=new T.TextureLoader(manager);P.forEach((p,i)=>{if(!p.art)return;texLoader.load(p.art,tex=>{tex.colorSpace=T.SRGBColorSpace;const ratio=tex.image&&tex.image.width&&tex.image.height?tex.image.width/tex.image.height:1.6,h=.62,w=Math.min(1.45,h*ratio),panel=new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({map:tex,transparent:true,toneMapped:false,side:T.DoubleSide}));panel.position.copy(stops[i]).add(new T.Vector3(0,1.72,.04));panel.lookAt(0,1.1,0);world.add(panel)},undefined,()=>{})})}
const moteN=low?36:120,motePos=new Float32Array(moteN*3);for(let i=0;i<moteN;i++){motePos[i*3]=(rand()-.5)*26;motePos[i*3+1]=groundY+.5+rand()*8;motePos[i*3+2]=(rand()-.5)*18}const mg=new T.BufferGeometry();mg.setAttribute('position',new T.BufferAttribute(motePos,3));const motes=new T.Points(mg,new T.PointsMaterial({color:0x91ffb5,size:low?.025:.035,transparent:true,opacity:.32,depthWrite:false}));world.add(motes);
let selected=0,segment=0,progress=0,paused=reduced,dwell=1.1,endHold=0;const segTime=low?3.1:2.75;
function setState(i,state){const p=P[i]||P[0];if(status)status.textContent=state+' · '+p.name+' · '+p.year}
function card(i){if(!mobileCard)return;const p=P[i],link=p.repo?'<a href="'+p.repo+'" target="_blank" rel="noopener">REPO ↗</a>':'<a href="#'+p.target+'">VIEW ↓</a>';mobileCard.innerHTML='<span class="tm-index">'+String(i+1).padStart(2,'0')+'</span><span class="tm-copy"><b>'+p.name+'</b><span>'+p.year+' · PROJECT STOP</span></span>'+link}
function select(i,jump){selected=Math.max(0,Math.min(P.length-1,i));labelEls.forEach((e,n)=>e.classList.toggle('active',n===selected));rings.forEach((r,n)=>{r.material.color.setHex(n===selected?PINK:n<selected?YELLOW:GREEN);r.scale.setScalar(n===selected?1.18:1)});card(selected);setState(selected,jump?'SELECTED':'ARRIVING');if(jump){segment=Math.min(selected,P.length-2);progress=selected===P.length-1?1:0;dwell=.8;vehicle.position.copy(stops[selected]).add(new T.Vector3(0,.14,0))}}
function restart(){selected=0;segment=0;progress=0;dwell=1.1;endHold=0;paused=reduced;vehicle.position.copy(stops[0]).add(new T.Vector3(0,.14,0));select(0,false);if(pauseBtn)pauseBtn.textContent=paused?'RESUME':'PAUSE'}
pauseBtn&&pauseBtn.addEventListener('click',()=>{paused=!paused;pauseBtn.textContent=paused?'RESUME':'PAUSE';setState(selected,paused?'PAUSED':'RUNNING')});replayBtn&&replayBtn.addEventListener('click',restart);nextBtn&&nextBtn.addEventListener('click',()=>{const n=Math.min(P.length-1,selected+1);n===selected?restart():select(n,true)});
let drag=false,sx=0,sy=0,sTheta=0,sPhi=0,moved=0,lastInteraction=performance.now();stage.addEventListener('pointerdown',e=>{drag=true;moved=0;sx=e.clientX;sy=e.clientY;sTheta=tTheta;sPhi=tPhi;lastInteraction=performance.now();stage.setPointerCapture&&stage.setPointerCapture(e.pointerId)});stage.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-sx,dy=e.clientY-sy;moved=Math.max(moved,Math.abs(dx)+Math.abs(dy));tTheta=sTheta-dx*(low?.0045:.006);tPhi=Math.max(.48,Math.min(1.28,sPhi+dy*(low?.0035:.0048)))});const release=e=>{drag=false;try{stage.releasePointerCapture&&stage.releasePointerCapture(e.pointerId)}catch(_){}};stage.addEventListener('pointerup',release);stage.addEventListener('pointercancel',release);stage.addEventListener('wheel',e=>{if(isMobile())return;tRadius=Math.max(11.8,Math.min(23,tRadius+Math.sign(e.deltaY)*.72));lastInteraction=performance.now();e.preventDefault()},{passive:false});
const ray=new T.Raycaster(),mouse=new T.Vector2();stage.addEventListener('click',e=>{if(moved>9)return;const r=stage.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height*2-1));ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(stationMeshes,false)[0];if(hit)select(hit.object.userData.index,true)});
function resize(){const r=stage.getBoundingClientRect(),w=Math.max(320,r.width||900),h=Math.max(isMobile()?450:520,r.height||600);renderer.setPixelRatio(Math.min(devicePixelRatio||1,low?1:1.45));renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();tRadius=low?18.8:Math.max(12.5,Math.min(tRadius,19))}if(window.ResizeObserver)new ResizeObserver(resize).observe(stage);else addEventListener('resize',resize,{passive:true});resize();
function labels(){if(isMobile())return;const r=stage.getBoundingClientRect();stops.forEach((p,i)=>{const el=labelEls[i];if(!el)return;const q=p.clone().add(new T.Vector3(0,1.7,0)).project(camera);el.style.left=Math.max(55,Math.min(r.width-55,(q.x*.5+.5)*r.width))+'px';el.style.top=Math.max(70,Math.min(r.height-35,(-q.y*.5+.5)*r.height))+'px';el.style.opacity=q.z>1?'0':'1'})}
let stageVisible=true,pageVisible=!document.hidden,lastRender=0,lastAnim=performance.now();if(window.IntersectionObserver)new IntersectionObserver(e=>{stageVisible=!!e[0]&&e[0].isIntersecting},{rootMargin:'180px 0px',threshold:.01}).observe(stage);document.addEventListener('visibilitychange',()=>{pageVisible=!document.hidden;lastAnim=performance.now()});
const forward=new T.Vector3(1,0,0);
function animate(now){requestAnimationFrame(animate);if(!stageVisible||!pageVisible){lastAnim=now;return}const fps=low?40:60,min=1000/fps;if(now-lastRender<min)return;lastRender=now;const dt=Math.min((now-lastAnim)/1000,.05);lastAnim=now;theta+=(tTheta-theta)*.075;phi+=(tPhi-phi)*.075;radius+=(tRadius-radius)*.075;if(!drag&&!isMobile()&&now-lastInteraction>5000)tTheta+=.00055;camera.position.set(Math.sin(theta)*Math.sin(phi)*radius,Math.cos(phi)*radius+1.1,Math.cos(theta)*Math.sin(phi)*radius);camera.lookAt(0,-.25,0);if(!paused){if(endHold>0){endHold-=dt;if(endHold<=0)restart()}else if(dwell>0)dwell-=dt;else if(segment<P.length-1){progress+=dt/segTime;const local=Math.min(1,progress),u=(segment+local)/(P.length-1),pos=curve.getPoint(u),tan=curve.getTangent(u).normalize();vehicle.position.copy(pos).add(new T.Vector3(0,.14,0));vehicle.quaternion.setFromUnitVectors(forward,tan);if(local>=1){segment++;progress=0;select(segment,false);dwell=segment===P.length-1?1.8:1;if(segment===P.length-1)endHold=2.8}else setState(segment+1,'EN ROUTE TO')}}if(mixer)mixer.update(dt);rings.forEach((r,i)=>r.rotation.z+=(i%2?1:-1)*(low?.0025:.0045));headLight.intensity=(low?1:1.9)+Math.sin(now*.009)*.25;motes.rotation.y+=low?.00015:.0003;labels();renderer.render(scene,camera)}
restart();stage.classList.add('three-live');setState(0,GLTFLoader?'WORLD ONLINE · LOADING ASSETS':'WORLD ONLINE · FALLBACK VEHICLE');requestAnimationFrame(animate);
})();